import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Apartment from './models/Apartment.js';

dotenv.config();

const sampleApartments = [
  {
    title: 'Luxury Studio in District 1 - City View',
    address: '22 Nguyen Hue, Ben Nghe Ward',
    district: 'District 1',
    city: 'Ho Chi Minh City',
    price: 850,
    area: 38,
    bedrooms: 0,
    bathrooms: 1,
    maxOccupants: 2,
    rooms: 1,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Gym', 'Pool', '24/7 Security', 'Balcony'],
    description: 'Modern studio apartment in the heart of District 1 with stunning city views. Fully furnished, perfect for expats. Walking distance to Bitexco Tower and Nguyen Hue walking street.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: true,
  },
  {
    title: 'Spacious 2BR Apartment - Thao Dien',
    address: '15 Nguyen Van Huong, Thao Dien',
    district: 'District 2',
    city: 'Ho Chi Minh City',
    price: 1400,
    area: 85,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    rooms: 4,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Dryer', 'Gym', 'Pool', 'Parking', 'Garden', '24/7 Security'],
    description: 'Beautiful apartment in the popular expat area of Thao Dien. Close to international schools, cafes and restaurants. Bright and airy with a large balcony.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    furnished: true,
    petFriendly: true,
    nearMetro: false,
  },
  {
    title: 'Modern 1BR near Landmark 81',
    address: '208 Nguyen Huu Canh, Binh Thanh',
    district: 'Binh Thanh',
    city: 'Ho Chi Minh City',
    price: 950,
    area: 55,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    rooms: 2,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Gym', 'Pool', 'Concierge', 'City View'],
    description: 'Stylish one-bedroom apartment with direct view of Landmark 81. High floor, modern furniture, perfect for professionals.',
    images: [
      'https://images.unsplash.com/photo-1502672023488-70e2581ebc2d?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: true,
  },
  {
    title: 'Family 3BR Villa-style Apartment - Phu My Hung',
    address: '12 My Phu 1, Tan Phong Ward',
    district: 'District 7',
    city: 'Ho Chi Minh City',
    price: 1800,
    area: 120,
    bedrooms: 3,
    bathrooms: 2,
    maxOccupants: 6,
    rooms: 5,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Dryer', 'Gym', 'Pool', 'Parking', 'Playground', '24/7 Security', 'Garden'],
    description: 'Spacious family apartment in the green and quiet Phu My Hung area. Ideal for families with children. Close to international schools and Crescent Mall.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    furnished: true,
    petFriendly: true,
    nearMetro: false,
  },
  {
    title: 'Cozy Studio - District 3',
    address: '45 Vo Van Tan, Ward 6',
    district: 'District 3',
    city: 'Ho Chi Minh City',
    price: 650,
    area: 32,
    bedrooms: 0,
    bathrooms: 1,
    maxOccupants: 2,
    rooms: 1,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Balcony'],
    description: 'Affordable and cozy studio in the quiet yet central District 3. Great for digital nomads and young professionals. Close to many cafes and co-working spaces.',
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: false,
  },
  {
    title: 'Premium 2BR Penthouse - District 1',
    address: '88 Dong Khoi, Ben Nghe',
    district: 'District 1',
    city: 'Ho Chi Minh City',
    price: 2200,
    area: 110,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    rooms: 4,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Dryer', 'Gym', 'Pool', 'Concierge', 'Rooftop Terrace', 'City View', '24/7 Security'],
    description: 'Exclusive penthouse with panoramic views of the Saigon River and city skyline. High-end finishes, private rooftop access. The ultimate luxury living experience.',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: true,
  },
  {
    title: 'Bright 1BR - Binh Thanh near Saigon Bridge',
    address: '102 Dien Bien Phu, Ward 15',
    district: 'Binh Thanh',
    city: 'Ho Chi Minh City',
    price: 780,
    area: 48,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    rooms: 2,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Balcony', 'Parking'],
    description: 'Well-lit apartment with modern interior. Convenient location near Saigon Bridge and many restaurants. Good value for money.',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    furnished: true,
    petFriendly: true,
    nearMetro: false,
  },
  {
    title: 'Serviced Apartment 2BR - District 2',
    address: '28 Quoc Huong, Thao Dien',
    district: 'District 2',
    city: 'Ho Chi Minh City',
    price: 1600,
    area: 95,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    rooms: 4,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Dryer', 'Gym', 'Pool', 'Housekeeping', 'Concierge', 'Parking'],
    description: 'Fully serviced apartment with weekly housekeeping included. Perfect for expats who want a hassle-free lifestyle in Thao Dien.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: false,
  },
  {
    title: 'Luxury Studio in District 1 - City View',
    address: '22 Nguyen Hue, Ben Nghe Ward',
    district: 'District 1',
    city: 'Ho Chi Minh City',
    price: 850,
    area: 38,
    bedrooms: 0,
    bathrooms: 1,
    maxOccupants: 2,
    rooms: 1,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Gym', 'Pool', '24/7 Security', 'Balcony'],
    description: 'Modern studio apartment in the heart of District 1 with stunning city views. Fully furnished, perfect for expats. Walking distance to Bitexco Tower and Nguyen Hue walking street.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: true,
  },
  {
    title: 'Spacious 2BR Apartment - Thao Dien',
    address: '15 Nguyen Van Huong, Thao Dien',
    district: 'District 2',
    city: 'Ho Chi Minh City',
    price: 1400,
    area: 85,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    rooms: 4,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Dryer', 'Gym', 'Pool', 'Parking', 'Garden', '24/7 Security'],
    description: 'Beautiful apartment in the popular expat area of Thao Dien. Close to international schools, cafes and restaurants. Bright and airy with a large balcony.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    furnished: true,
    petFriendly: true,
    nearMetro: false,
  },
  {
    title: 'Modern 1BR near Landmark 81',
    address: '208 Nguyen Huu Canh, Binh Thanh',
    district: 'Binh Thanh',
    city: 'Ho Chi Minh City',
    price: 950,
    area: 55,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    rooms: 2,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Gym', 'Pool', 'Concierge', 'City View'],
    description: 'Stylish one-bedroom apartment with direct view of Landmark 81. High floor, modern furniture, perfect for professionals.',
    images: [
      'https://images.unsplash.com/photo-1502672023488-70e2581ebc2d?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: true,
  },
  {
    title: 'Family 3BR Villa-style Apartment - Phu My Hung',
    address: '12 My Phu 1, Tan Phong Ward',
    district: 'District 7',
    city: 'Ho Chi Minh City',
    price: 1800,
    area: 120,
    bedrooms: 3,
    bathrooms: 2,
    maxOccupants: 6,
    rooms: 5,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Dryer', 'Gym', 'Pool', 'Parking', 'Playground', '24/7 Security', 'Garden'],
    description: 'Spacious family apartment in the green and quiet Phu My Hung area. Ideal for families with children. Close to international schools and Crescent Mall.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    furnished: true,
    petFriendly: true,
    nearMetro: false,
  },
  {
    title: 'Cozy Studio - District 3',
    address: '45 Vo Van Tan, Ward 6',
    district: 'District 3',
    city: 'Ho Chi Minh City',
    price: 650,
    area: 32,
    bedrooms: 0,
    bathrooms: 1,
    maxOccupants: 2,
    rooms: 1,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Balcony'],
    description: 'Affordable and cozy studio in the quiet yet central District 3. Great for digital nomads and young professionals. Close to many cafes and co-working spaces.',
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: false,
  },
  {
    title: 'Premium 2BR Penthouse - District 1',
    address: '88 Dong Khoi, Ben Nghe',
    district: 'District 1',
    city: 'Ho Chi Minh City',
    price: 2200,
    area: 110,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    rooms: 4,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Dryer', 'Gym', 'Pool', 'Concierge', 'Rooftop Terrace', 'City View', '24/7 Security'],
    description: 'Exclusive penthouse with panoramic views of the Saigon River and city skyline. High-end finishes, private rooftop access. The ultimate luxury living experience.',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: true,
  },
  {
    title: 'Bright 1BR - Binh Thanh near Saigon Bridge',
    address: '102 Dien Bien Phu, Ward 15',
    district: 'Binh Thanh',
    city: 'Ho Chi Minh City',
    price: 780,
    area: 48,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    rooms: 2,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Balcony', 'Parking'],
    description: 'Well-lit apartment with modern interior. Convenient location near Saigon Bridge and many restaurants. Good value for money.',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    furnished: true,
    petFriendly: true,
    nearMetro: false,
  },
  {
    title: 'Serviced Apartment 2BR - District 2',
    address: '28 Quoc Huong, Thao Dien',
    district: 'District 2',
    city: 'Ho Chi Minh City',
    price: 1600,
    area: 95,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    rooms: 4,
    amenities: ['Air Conditioning', 'Wi-Fi', 'Washing Machine', 'Dryer', 'Gym', 'Pool', 'Housekeeping', 'Concierge', 'Parking'],
    description: 'Fully serviced apartment with weekly housekeeping included. Perfect for expats who want a hassle-free lifestyle in Thao Dien.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    furnished: true,
    petFriendly: false,
    nearMetro: false,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await Apartment.deleteMany({});
    console.log('Cleared old data');

    await Apartment.insertMany(sampleApartments);
    console.log(`✅ Seeded ${sampleApartments.length} apartments successfully`);

    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();
